theme: jekyll-theme-cayman
title: "🌿 SadovodBNL"
description: "Очень категоричный гайд садоводов"
remote_theme: "just-the-docs/just-the-docs"

footer_content: "<a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ru\"><img alt=\"Лицензия Creative Commons\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png\" /></a><br />Это произведение доступно по <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ru\">лицензии Creative Commons «Attribution-NonCommercial-NoDerivatives» («Атрибуция-Некоммерчески-БезПроизводных») 4.0 Всемирная</a>."

search_enabled: false
search:
  button: false

ga_tracking: G-GKFKT99WR6

plugins:
  - jekyll-seo-tag
