# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SadovodBNL
site_description: "Очень категоричный справочник садовода"

nav:
  - index.md
  - Уход за растениями:
      - Борьба с вредителями:
          - plant-care/pest-control/insects.md
          - plant-care/pest-control/snails.md
          - plant-care/pest-control/ants.md
          - plant-care/pest-control/flies.md
          - plant-care/pest-control/house-spiders.md
      - plant-care/fungi.md
      - plant-care/fertilizers.md
  - Привлечение животных:
      - attracting-animals/birds.md
      - attracting-animals/hedgehogs.md
  - apps.md
  - contributing.md
  - sponsor.md

theme:
  favicon: "images/favicon.ico" # https://icon.kitchen/i/H4sIAAAAAAAAAyWOvQ7CMAyE38WsGYoES9eKHQk2xOAkThqR1iU%2FZaj67jiw2KfP1t1tsGKslKHfwGJ63UeaCPqSKilwfohhwVTaNZMssOSwxgIKguFZABmGXYH2A0dOAg4ng%2B7cyYf2txEXcYP8riGZSAKdv6K1YfbNs%2FAC%2FbFTkIIfxb5JzaXw9NeR3I9KgPMX58gUaQoUacVCLXdiW2Or%2FwCcbeJgWzXOMj%2Bk4bl%2FAefJD0PhAAAA
  logo: "images/icon-512.png"
  icon:
    repo: "material/github"
    tag:
      insects: "material/bug"
      birds: "material/bird"
      cats: "material/cat"
      solutions: "material/spray"
  name: material
  language: ru
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Системная тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Темная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Светлая тема

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
  - search:
      lang: ru
  - social
  - autorefs
  - tags
  - git-committers:
      repository: eigenein/sadovod-bnl
      branch: main

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

repo_url: https://github.com/eigenein/sadovod-bnl

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/gardening_benelux
      name: Чат в Telegram
    - icon: material/google-spreadsheet
      link: https://docs.google.com/spreadsheets/d/1Kb5VpLNyeKjFGBcfFL9tN5z-cKTSS4mMP1GA9QjMOzY/edit?usp=sharing
      name: Список растений
  analytics:
    provider: google
    property: G-GKFKT99WR6
  tags:
    Насекомые: insects
    Птицы: birds
    Коты: cats
    Средства: solutions

copyright: Copyright &copy; 2021-2023 SadovodBNL (CC BY-NC-ND 4.0)

site_url: "https://sadovod.nl"
edit_uri: edit/main/docs/

watch:
  - "docs"
