[tool.poetry]
name = "sadovod-bnl"
version = "1.0.0"
description = ""
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
license = "CC-BY-NC-ND-4.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.0"
mkdocs-material = "9.4.8"
Pillow = "10.1.0"
CairoSVG = "2.7.1"
mkdocs-git-revision-date-localized-plugin = "1.2.1"
mkdocs-autorefs = "0.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
